In [1]:
import numpy as np
import pandas as pd
import pickle
import sys
import os
import dsc
from dsc.query_engine import Query_Processor as dscQP
from dsc import dsc_io

import matplotlib.pyplot as plt
from pymir import mpl_stylesheet
from pymir import mpl_utils
mpl_stylesheet.banskt_presentation(splinecolor = 'black', dpi = 120)

sys.path.append("/gpfs/commons/home/sbanerjee/work/npd/lrma-dsc/post-process")
import dscrutils2py as dscrutils

INFO: cffi mode is CFFI_MODE.ANY
INFO: R home found: /nfs/sw/easybuild/software/R/4.4.1-gfbf-2023b/lib64/R
INFO: R library path: /nfs/sw/easybuild/software/R/4.4.1-gfbf-2023b/lib64/R/lib:/nfs/sw/easybuild/software/FriBidi/1.0.13-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/FriBidi/1.0.13-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/HarfBuzz/8.2.2-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/HarfBuzz/8.2.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/Tk/8.6.13-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/Tk/8.6.13-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/cURL/8.3.0-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/cURL/8.3.0-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/OpenSSL/1.1/lib64:/nfs/sw/easybuild/software/OpenSSL/1.1/lib:/nfs/sw/easybuild/software/libgit2/1.7.2-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/libgit2/1.7.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/Java/11.0.16/lib64:/nfs/sw/easybuild/software/Java/11.0.16/lib:/nfs/sw/easybuild/software/LibTIFF/4.6.0-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/LibTIFF/4.6.0-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libjpeg-turbo/3.0.1-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/libjpeg-turbo/3.0.1-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libpng/1.6.40-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/libpng/1.6.40-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/PCRE2/10.42-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/PCRE2/10.42-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/SQLite/3.43.1-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/SQLite/3.43.1-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/zlib/1.2.13-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/zlib/1.2.13-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/XZ/5.4.4-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/XZ/5.4.4-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/bzip2/1.0.8-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/bzip2/1.0.8-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/ncurses/6.4-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/ncurses/6.4-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libreadline/8.2-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/libreadline/8.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/cairo/1.18.0-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/cairo/1.18.0-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libGLU/9.0.3-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/libGLU/9.0.3-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/Mesa/23.1.9-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/Mesa/23.1.9-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/X11/20231019-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/X11/20231019-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/pkgconf/2.0.3-GCCcore-13.2.0/lib64:/nfs/sw/easybuild/software/pkgconf/2.0.3-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/FFTW/3.3.10-GCC-13.2.0/lib64:/nfs/sw/easybuild/software/FFTW/3.3.10-GCC-13.2.0/lib:/nfs/sw/easybuild/software/FlexiBLAS/3.3.1-GCC-13.2.0/lib64:/nfs/sw/easybuild/software/FlexiBLAS/3.3.1-GCC-13.2.0/lib:/nfs/sw/easybuild/software/GCCcore/13.2.0/lib64:/nfs/sw/easybuild/software/GCCcore/13.2.0/lib:/nfs/sw/easybuild/software/Tcl/8.6.13-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/Java/11.0.16/lib/server:/nfs/sw/easybuild/software/R/4.4.1-gfbf-2023b/libs:/nfs/sw/easybuild/software/R/4.4.1-gfbf-2023b/lib/R/lib:/nfs/sw/easybuild/software/GDAL/3.5.0-foss-2022a/lib:/nfs/sw/easybuild/software/HDF/4.2.15-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libtirpc/1.3.2-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libgeotiff/1.7.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/PROJ/9.0.0-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/PCRE/8.45-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/LibTIFF/4.3.0-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libdeflate/1.10-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/GCCcore/11.3.0/lib64:/nfs/sw/easybuild/software/zstd/1.5.2-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/jbigkit/2.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/XZ/5.2.5-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libjpeg-turbo/2.1.3-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/zlib/1.2.12-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/JasPer/2.0.33-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libpng/1.6.37-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/GEOS/3.10.3-GCC-11.3.0/lib:/nfs/sw/easybuild/software/netCDF/4.9.0-gompi-2022a/lib:/nfs/sw/easybuild/software/lz4/1.9.3-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/cURL/7.83.0-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/HDF5/1.12.2-gompi-2022a/lib:/nfs/sw/easybuild/software/Szip/2.1.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/Python/3.10.4-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libffi/3.4.2-GCCcore-11.3.0/lib64:/nfs/sw/easybuild/software/GMP/6.2.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/SQLite/3.38.3-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/Tcl/8.6.12-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libreadline/8.1.2-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/bzip2/1.0.8-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/ScaLAPACK/2.2.0-gompi-2022a-fb/lib:/nfs/sw/easybuild/software/FFTW.MPI/3.3.10-gompi-2022a/lib:/nfs/sw/easybuild/software/FFTW/3.3.10-GCC-11.3.0/lib:/nfs/sw/easybuild/software/FlexiBLAS/3.2.0-GCC-11.3.0/lib:/nfs/sw/easybuild/software/OpenBLAS/0.3.20-GCC-11.3.0/lib:/nfs/sw/easybuild/software/OpenMPI/4.1.4-GCC-11.3.0/lib:/nfs/sw/easybuild/software/UCC/1.0.0-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/PMIx/4.1.2-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libfabric/1.15.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/UCX/1.12.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libevent/2.1.12-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/hwloc/2.7.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libpciaccess/0.16-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libxml2/2.9.13-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/numactl/2.0.14-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/binutils/2.38-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/FriBidi/1.0.13-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/HarfBuzz/8.2.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/cairo/1.18.0-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/pixman/0.42.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/ICU/74.1-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/GLib/2.78.1-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/gettext/0.22-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libiconv/1.17-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/Tk/8.6.13-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libgit2/1.7.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/OpenSSL/1.1/lib:/nfs/sw/easybuild/software/Java/11.0.16/lib:/nfs/sw/easybuild/software/PCRE2/10.42-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libGLU/9.0.3-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/Mesa/23.1.9-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/Wayland/1.22.0-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/LLVM/16.0.6-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libunwind/1.6.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libglvnd/1.7.0-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libdrm/2.4.117-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/X11/20231019-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/fontconfig/2.14.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/util-linux/2.39-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/freetype/2.13.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/Brotli/1.1.0-GCCcore-13.2.0/lib:/opt/slurm/slurm-24.05.2/lib:/opt/slurm/slurm-24.05.2/lib/slurm::
INFO: LD_LIBRARY_PATH: /nfs/sw/easybuild/software/R/4.4.1-gfbf-2023b/libs:/nfs/sw/easybuild/software/R/4.4.1-gfbf-2023b/lib/R/lib:/nfs/sw/easybuild/software/GDAL/3.5.0-foss-2022a/lib:/nfs/sw/easybuild/software/HDF/4.2.15-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libtirpc/1.3.2-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libgeotiff/1.7.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/PROJ/9.0.0-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/PCRE/8.45-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/LibTIFF/4.3.0-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libdeflate/1.10-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/GCCcore/11.3.0/lib64:/nfs/sw/easybuild/software/zstd/1.5.2-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/jbigkit/2.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/XZ/5.2.5-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libjpeg-turbo/2.1.3-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/zlib/1.2.12-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/JasPer/2.0.33-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libpng/1.6.37-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/GEOS/3.10.3-GCC-11.3.0/lib:/nfs/sw/easybuild/software/netCDF/4.9.0-gompi-2022a/lib:/nfs/sw/easybuild/software/lz4/1.9.3-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/cURL/7.83.0-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/HDF5/1.12.2-gompi-2022a/lib:/nfs/sw/easybuild/software/Szip/2.1.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/Python/3.10.4-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libffi/3.4.2-GCCcore-11.3.0/lib64:/nfs/sw/easybuild/software/GMP/6.2.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/SQLite/3.38.3-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/Tcl/8.6.12-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libreadline/8.1.2-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/bzip2/1.0.8-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/ScaLAPACK/2.2.0-gompi-2022a-fb/lib:/nfs/sw/easybuild/software/FFTW.MPI/3.3.10-gompi-2022a/lib:/nfs/sw/easybuild/software/FFTW/3.3.10-GCC-11.3.0/lib:/nfs/sw/easybuild/software/FlexiBLAS/3.2.0-GCC-11.3.0/lib:/nfs/sw/easybuild/software/OpenBLAS/0.3.20-GCC-11.3.0/lib:/nfs/sw/easybuild/software/OpenMPI/4.1.4-GCC-11.3.0/lib:/nfs/sw/easybuild/software/UCC/1.0.0-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/PMIx/4.1.2-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libfabric/1.15.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/UCX/1.12.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libevent/2.1.12-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/hwloc/2.7.1-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libpciaccess/0.16-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/libxml2/2.9.13-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/numactl/2.0.14-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/binutils/2.38-GCCcore-11.3.0/lib:/nfs/sw/easybuild/software/FriBidi/1.0.13-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/HarfBuzz/8.2.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/cairo/1.18.0-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/pixman/0.42.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/ICU/74.1-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/GLib/2.78.1-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/gettext/0.22-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libiconv/1.17-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/Tk/8.6.13-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libgit2/1.7.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/OpenSSL/1.1/lib:/nfs/sw/easybuild/software/Java/11.0.16/lib:/nfs/sw/easybuild/software/PCRE2/10.42-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libGLU/9.0.3-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/Mesa/23.1.9-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/Wayland/1.22.0-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/LLVM/16.0.6-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libunwind/1.6.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libglvnd/1.7.0-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/libdrm/2.4.117-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/X11/20231019-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/fontconfig/2.14.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/util-linux/2.39-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/freetype/2.13.2-GCCcore-13.2.0/lib:/nfs/sw/easybuild/software/Brotli/1.1.0-GCCcore-13.2.0/lib:/opt/slurm/slurm-24.05.2/lib:/opt/slurm/slurm-24.05.2/lib/slurm
INFO: Default options to initialize R: rpy2, --quiet, --no-save
INFO: R is already initialized. No need to initialize.

In [2]:
def stratify_dfcol(df, colname, value):
    #return pd_utils.select_dfrows(df, [f"$({colname}) == {value}"])
    return df.loc[df[colname] == value]

def stratify_dfcols(df, condition_list):
    for (colname, value) in condition_list:
        df = stratify_dfcol(df, colname, value)
    return df

def stratify_dfcols_in_list(df, colname, values):
    return df.loc[df[colname].isin(values)]

In [3]:
dsc_output = "/gpfs/commons/groups/knowles_lab/sbanerjee/low_rank_matrix_approximation_numerical_experiments/lrma"
dsc_fname  = os.path.basename(os.path.normpath(dsc_output))
db = os.path.join(dsc_output, dsc_fname + ".db")
# dscoutpkl = os.path.join("/gpfs/commons/home/sbanerjee/work/npd/lrma-dsc/dsc/results", dsc_fname + "_dscout.pkl")
# dscout    = pd.read_pickle(dscoutpkl)
# dscout

In [4]:
targets = ["simulate"] + \
            [f"simulate.{x}" for x in ["n", "p", "k", "h2", "h2_shared_frac", "aq"]] + \
            ["lowrankfit", "mfmethods"] + \
            [f"score.{x}" for x in ["L_rmse", "F_rmse", "Z_rmse", "L_psnr", "F_psnr", "Z_psnr", "MI", "adj_MI"]]

qp = dscQP(db, targets)
df = qp.output_table
df

,DSC,simulate,simulate.p,simulate.output.file,simulate.n,simulate.k,simulate.h2_shared_frac,simulate.h2,simulate.aq,lowrankfit,...,mfmethods,mfmethods.output.file,score.L_rmse:output,score.F_rmse:output,score.Z_rmse:output,score.L_psnr:output,score.F_psnr:output,score.Z_psnr:output,score.MI:output,score.adj_MI:output
0,1,blockdiag,2000.0,blockdiag/blockdiag_1,200.0,10.0,0.6,0.2,0.6,rpca,...,truncated_svd,truncated_svd/blockdiag_1_rpca_1_truncated_svd_1,score/blockdiag_21_rpca_3_truncated_svd_3_score_3,score/blockdiag_21_rpca_3_truncated_svd_3_score_3,score/blockdiag_21_rpca_3_truncated_svd_3_score_3,score/blockdiag_21_rpca_3_truncated_svd_3_score_3,score/blockdiag_21_rpca_3_truncated_svd_3_score_3,score/blockdiag_21_rpca_3_truncated_svd_3_score_3,score/blockdiag_21_rpca_3_truncated_svd_3_score_3,score/blockdiag_21_rpca_3_truncated_svd_3_score_3
1,2,blockdiag,2000.0,blockdiag/blockdiag_2,200.0,10.0,0.6,0.2,0.6,rpca,...,truncated_svd,truncated_svd/blockdiag_2_rpca_1_truncated_svd_1,score/blockdiag_22_rpca_3_truncated_svd_3_score_3,score/blockdiag_22_rpca_3_truncated_svd_3_score_3,score/blockdiag_22_rpca_3_truncated_svd_3_score_3,score/blockdiag_22_rpca_3_truncated_svd_3_score_3,score/blockdiag_22_rpca_3_truncated_svd_3_score_3,score/blockdiag_22_rpca_3_truncated_svd_3_score_3,score/blockdiag_22_rpca_3_truncated_svd_3_score_3,score/blockdiag_22_rpca_3_truncated_svd_3_score_3
2,3,blockdiag,2000.0,blockdiag/blockdiag_3,200.0,10.0,0.6,0.2,0.6,rpca,...,truncated_svd,truncated_svd/blockdiag_3_rpca_1_truncated_svd_1,score/blockdiag_23_rpca_3_truncated_svd_3_score_3,score/blockdiag_23_rpca_3_truncated_svd_3_score_3,score/blockdiag_23_rpca_3_truncated_svd_3_score_3,score/blockdiag_23_rpca_3_truncated_svd_3_score_3,score/blockdiag_23_rpca_3_truncated_svd_3_score_3,score/blockdiag_23_rpca_3_truncated_svd_3_score_3,score/blockdiag_23_rpca_3_truncated_svd_3_score_3,score/blockdiag_23_rpca_3_truncated_svd_3_score_3
3,4,blockdiag,2000.0,blockdiag/blockdiag_4,200.0,10.0,0.6,0.2,0.6,rpca,...,truncated_svd,truncated_svd/blockdiag_4_rpca_1_truncated_svd_1,score/blockdiag_24_rpca_3_truncated_svd_3_score_3,score/blockdiag_24_rpca_3_truncated_svd_3_score_3,score/blockdiag_24_rpca_3_truncated_svd_3_score_3,score/blockdiag_24_rpca_3_truncated_svd_3_score_3,score/blockdiag_24_rpca_3_truncated_svd_3_score_3,score/blockdiag_24_rpca_3_truncated_svd_3_score_3,score/blockdiag_24_rpca_3_truncated_svd_3_score_3,score/blockdiag_24_rpca_3_truncated_svd_3_score_3
4,5,blockdiag,2000.0,blockdiag/blockdiag_5,200.0,10.0,0.6,0.2,0.6,rpca,...,truncated_svd,truncated_svd/blockdiag_5_rpca_1_truncated_svd_1,score/blockdiag_25_rpca_3_truncated_svd_3_score_3,score/blockdiag_25_rpca_3_truncated_svd_3_score_3,score/blockdiag_25_rpca_3_truncated_svd_3_score_3,score/blockdiag_25_rpca_3_truncated_svd_3_score_3,score/blockdiag_25_rpca_3_truncated_svd_3_score_3,score/blockdiag_25_rpca_3_truncated_svd_3_score_3,score/blockdiag_25_rpca_3_truncated_svd_3_score_3,score/blockdiag_25_rpca_3_truncated_svd_3_score_3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1705,8,blockdiag_aq,2000.0,blockdiag_aq/blockdiag_aq_16,200.0,10.0,0.6,0.2,0.8,NA,...,factorgo,factorgo/blockdiag_aq_16_identical_1_factorgo_1,score/blockdiag_aq_56_identical_3_factorgo_3_s...,score/blockdiag_aq_56_identical_3_factorgo_3_s...,score/blockdiag_aq_56_identical_3_factorgo_3_s...,score/blockdiag_aq_56_identical_3_factorgo_3_s...,score/blockdiag_aq_56_identical_3_factorgo_3_s...,score/blockdiag_aq_56_identical_3_factorgo_3_s...,score/blockdiag_aq_56_identical_3_factorgo_3_s...,score/blockdiag_aq_56_identical_3_factorgo_3_s...
1706,9,blockdiag_aq,2000.0,blockdiag_aq/blockdiag_aq_17,200.0,10.0,0.6,0.2,0.4,NA,...,factorgo,factorgo/blockdiag_aq_17_identical_1_factorgo_1,score/blockdiag_aq_57_identical_3_factorgo_3_s...,score/blockdiag_aq_57_identical_3_factorgo_3_s...,score/blockdiag_aq_57_identical_3_factorgo_3_s...,score/blockdiag_aq_57_identical_3_factorgo_3_s...,score/blockdiag_aq_57_identical_3_factorgo_3_s...,score/blockdiag_aq_57_identical_3_factorgo_3_s...,score/blockdiag_aq_57_identical_3_factorgo_3_s...,score/blockdiag_aq_57_identical_3_factorgo_3_s...
1707,9,blockdiag_aq,2000.0,blockdiag_aq/blockdiag_aq_18,200.0,10.0,0.6,0.2,0.8,NA,...,factorgo,factorgo/blockdiag_aq_18_identical_1_factorgo_1,score/blockdiag_aq_58_identical_3_factorgo_3_s...,score/blockdiag_aq_58_identical_3_factorgo_3_s...,score/blockdiag_aq_58_identical_3_factorgo_3_s...,score/blockdiag_aq_58_identical_3_factorgo_3_s...,score/blockdiag_aq_58_identical_3_factorgo_3_s...,score/blockdiag_aq_58_identical_3_factorgo_3_s...,score/blockdiag_aq_58_identical_3_factorgo_3_s...,score/blockdiag_aq_58_identical_3_factorgo_3_s...
1708,10,blockdiag_aq,2000.0,blockdiag_aq/blockdiag_aq_19,200.0,10.0,0.6,0.2,0.4,NA,...,factorgo,factorgo/blockdiag_aq_19_identical_1_factorgo_1,score/blockdiag_aq_59_identical_3_factorgo_3_s...,score/blockdiag_aq_59_identical_3_factorgo_3_s...,score/blockdiag_aq_59_identical_3_factorgo_3_s...,score/blockdiag_aq_59_identical_3_factorgo_3_s...,score/blockdiag_aq_59_identical_3_factorgo_3_s...,score/blockdiag_aq_59_identical_3_factorgo_3_s...,score/blockdiag_aq_59_identical_3_factorgo_3_s...,score/blockdiag_aq_59_identical_3_factorgo_3_s...
1709,10,blockdiag_aq,2000.0,blockdiag_aq/blockdiag_aq_20,200.0,10.0,0.6,0.2,0.8,NA,...,factorgo,factorgo/blockdiag_aq_20_identical_1_factorgo_1,score/blockdiag_aq_60_identical_3_factorgo_3_s...,score/blockdiag_aq_60_identical_3_factorgo_3_s...,score/blockdiag_aq_60_identical_3_factorgo_3_s...,score/blockdiag_aq_60_identical_3_factorgo_3_s...,score/blockdiag_aq_60_identical_3_factorgo_3_s...,score/blockdiag_aq_60_identical_3_factorgo_3_s...,score/blockdiag_aq_60_identical_3_factorgo_3_s...,score/blockdiag_aq_60_identical_3_factorgo_3_s...

In [5]:
df.columns

Index(['DSC', 'simulate', 'simulate.p', 'simulate.output.file', 'simulate.n',
       'simulate.k', 'simulate.h2_shared_frac', 'simulate.h2', 'simulate.aq',
       'lowrankfit', 'lowrankfit.output.file', 'mfmethods',
       'mfmethods.output.file', 'score.L_rmse:output', 'score.F_rmse:output',
       'score.Z_rmse:output', 'score.L_psnr:output', 'score.F_psnr:output',
       'score.Z_psnr:output', 'score.adj_MI:output'],
      dtype='object')

In [7]:
df.loc[[753]]

,DSC,simulate,simulate.p,simulate.output.file,simulate.n,simulate.k,simulate.h2_shared_frac,simulate.h2,simulate.aq,lowrankfit,...,mfmethods,mfmethods.output.file,score.L_rmse:output,score.F_rmse:output,score.Z_rmse:output,score.L_psnr:output,score.F_psnr:output,score.Z_psnr:output,score.MI:output,score.adj_MI:output
753,1,blockdiag_p,10000.0,blockdiag_p/blockdiag_p_4,200.0,10.0,0.6,0.2,0.6,NA,...,gleanr,gleanr/blockdiag_p_4_identical_1_gleanr_1,score/blockdiag_p_84_identical_3_gleanr_3_score_3,score/blockdiag_p_84_identical_3_gleanr_3_score_3,score/blockdiag_p_84_identical_3_gleanr_3_score_3,score/blockdiag_p_84_identical_3_gleanr_3_score_3,score/blockdiag_p_84_identical_3_gleanr_3_score_3,score/blockdiag_p_84_identical_3_gleanr_3_score_3,score/blockdiag_p_84_identical_3_gleanr_3_score_3,score/blockdiag_p_84_identical_3_gleanr_3_score_3

In [8]:
df.loc[753]

DSC                                                                        1
simulate                                                         blockdiag_p
simulate.p                                                           10000.0
simulate.output.file                               blockdiag_p/blockdiag_p_4
simulate.n                                                             200.0
simulate.k                                                              10.0
simulate.h2_shared_frac                                                  0.6
simulate.h2                                                              0.2
simulate.aq                                                              0.6
lowrankfit                                                                NA
lowrankfit.output.file                                                    NA
mfmethods                                                             gleanr
mfmethods.output.file              gleanr/blockdiag_p_4_identical_1_gleanr_1
score.L_rmse:output        score/blockdiag_p_84_identical_3_gleanr_3_score_3
score.F_rmse:output        score/blockdiag_p_84_identical_3_gleanr_3_score_3
score.Z_rmse:output        score/blockdiag_p_84_identical_3_gleanr_3_score_3
score.L_psnr:output        score/blockdiag_p_84_identical_3_gleanr_3_score_3
score.F_psnr:output        score/blockdiag_p_84_identical_3_gleanr_3_score_3
score.Z_psnr:output        score/blockdiag_p_84_identical_3_gleanr_3_score_3
score.MI:output            score/blockdiag_p_84_identical_3_gleanr_3_score_3
score.adj_MI:output        score/blockdiag_p_84_identical_3_gleanr_3_score_3
Name: 753, dtype: object

In [8]:
gleanr_res = dsc_io.load_dsc(os.path.join(dsc_output, "gleanr/blockdiag_p_7_identical_1_gleanr_1.rds"))
sim_input = dsc_io.load_dsc(os.path.join(dsc_output, "blockdiag_p/blockdiag_p_7.pkl"))

In [9]:
gleanr_res.keys()

dict_keys(['L_est', 'F_est', 'S2', 'DSC_DEBUG'])

In [10]:
sim_input.keys()

dict_keys(['Z', 'Zmask', 'effect_size_obs', 'effect_size_true', 'Ltrue', 'Ftrue', 'Mtrue', 'Ctrue', 'nsample', 'DSC_DEBUG'])

In [11]:
sys.path.append("/gpfs/commons/home/sbanerjee/work/npd/lrma-dsc/dsc/functions")

from comparison_metrics import matrix_dissimilarity_scores
from comparison_metrics import adjusted_mutual_information_score
from comparison_metrics import root_mean_squared_error
from comparison_metrics import peak_signal_to_noise_ratio
from comparison_metrics import standardize

In [12]:
Ltrue = sim_input["Ltrue"]
Ftrue = sim_input["Ftrue"]
labels = sim_input["Ctrue"]
L = gleanr_res["L_est"]
F = gleanr_res["F_est"]

In [13]:
L_rmse, L_psnr = matrix_dissimilarity_scores(Ltrue, L)
F_rmse, F_psnr = matrix_dissimilarity_scores(Ftrue, F)
Ztrue = standardize(Ltrue @ Ftrue.T, axis = 0)
Zrecv = standardize(L @ F.T, axis = 0)
Z_rmse = root_mean_squared_error(Ztrue, Zrecv)
Z_psnr = peak_signal_to_noise_ratio(Ztrue, Zrecv)
MI, adj_MI = adjusted_mutual_information_score(L, labels)

In [14]:
Z_rmse

0.9123679256846536

In [19]:
dscout = dscrutils.dscquery(dsc_output, targets)

Calling: dsc-query /gpfs/commons/groups/knowles_lab/sbanerjee/low_rank_matrix_approximation_numerical_experiments/lrma_pilot -o /tmp/Rtmppllmze/file1125aa571280c2.csv --target "simulate simulate.n simulate.p simulate.k simulate.h2 simulate.h2_shared_frac simulate.aq lowrankfit mfmethods score.L_rmse score.F_rmse score.Z_rmse score.L_psnr score.F_psnr score.Z_psnr score.adj_MI" --force
Loaded dscquery output table with 6 rows and 20 columns.

In [20]:
dscout

,DSC,simulate,simulate.n,simulate.p,simulate.k,simulate.h2,simulate.h2_shared_frac,simulate.aq,lowrankfit,mfmethods,score.L_rmse,score.F_rmse,score.Z_rmse,score.L_psnr,score.F_psnr,score.Z_psnr,score.adj_MI
0,1,blockdiag,200,500,10,0.2,0.5,0.6,rpca,truncated_svd,0.318090,0.358677,0.007440,26.348389,26.053003,24.850847,0.834796
1,1,blockdiag,200,500,10,0.2,0.5,0.6,nnm,truncated_svd,0.343524,0.371516,0.007744,25.680260,25.747526,24.503876,0.820669
2,1,blockdiag,200,500,10,0.2,0.5,0.6,nnm_sparse,truncated_svd,0.343298,0.371412,0.007745,25.685974,25.749952,24.501851,0.828367
3,1,blockdiag,200,500,10,0.2,0.5,0.6,None,truncated_svd,0.346300,0.371384,0.006549,25.610347,25.750614,25.959193,0.006741
4,1,blockdiag,200,500,10,0.2,0.5,0.6,None,factorgo,0.401745,0.497179,0.004205,24.320396,23.216812,29.806612,0.017130
5,1,blockdiag,200,500,10,0.2,0.5,0.6,None,flashier,0.361294,0.428657,1.678715,25.242177,24.504877,-22.216785,0.042308